###########
# site.title

title:    'ICS-175-Group-6-Project'
subtitle: 'Text Sentiment Analysis System'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
